### ISSUE TITLE
Colcon Not Building

### ISSUE THREAD

**Issue by JamesTRoss1** [UniversalRobots/Universal_Robots_ROS2_Driver#159]
Hello, colon is not building properly after configuring ros foxy. Any help would be appreciated. 

bash: /opt/ros/melodic/setup.bash: No such file or directory
bash: /opt/ros/notic/setup.bash: No such file or directory
ROS_DISTRO was set to 'noetic' before. Please make sure that the environment does not mix paths from different distributions.
(base) birth@birth-Inspiron-7570:~$ sudo apt install python3-colcon-common-extensions python3-vcstool
[sudo] password for birth: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-colcon-common-extensions is already the newest version (0.2.1-1).
python3-vcstool is already the newest version (0.2.15-1).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
(base) birth@birth-Inspiron-7570:~$ export COLCON_WS=~/workspace/ros_ws_foxy_ur_driver
(base) birth@birth-Inspiron-7570:~$ cd $COLCON_WS
(base) birth@birth-Inspiron-7570:~/workspace/ros_ws_foxy_ur_driver$ source /opt/ros/foxy/setup.bash
(base) birth@birth-Inspiron-7570:~/workspace/ros_ws_foxy_ur_driver$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
Starting >>> control_msgs
Starting >>> ros2_control_test_assets
Starting >>> controller_manager_msgs
Starting >>> diffbot_description
Starting >>> ros2_control_test_nodes
Starting >>> rrbot_description                              
Starting >>> ur_client_library
Starting >>> ur_dashboard_msgs
[10.647s] ERROR:colcon.colcon_core.environment:Exception in shell extension 'dsv': [Errno 13] Permission denied: '/home/birth/workspace/ros_ws_foxy_ur_driver/install/diffbot_description/share/diffbot_description/package.dsv'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 131, in create_environment_scripts_only
    retval = extension.create_package_script(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/dsv.py", line 30, in create_package_script
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 55, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/birth/workspace/ros_ws_foxy_ur_driver/install/diffbot_description/share/diffbot_description/package.dsv'

--- stderr: diffbot_description                                   
CMake Error at ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:5 (file):
  file failed to open for writing (Permission denied):

    /home/birth/workspace/ros_ws_foxy_ur_driver/build/diffbot_description/symlink_install_manifest.txt
Call Stack (most recent call first):
  cmake_install.cmake:41 (include)

---
Failed   <<< diffbot_description [4.55s, exited with code 1]
Aborted  <<< rrbot_description [4.43s]
Aborted  <<< ros2_control_test_assets [4.57s]
Aborted  <<< ros2_control_test_nodes [4.55s]
Aborted  <<< ur_client_library [5.27s]                                       
Aborted  <<< ur_dashboard_msgs [8.08s]                                       
Aborted  <<< controller_manager_msgs [8.36s]                                 
Aborted  <<< control_msgs [8.86s]                            
                                  
Summary: 0 packages finished [10.0s]
  1 package failed: diffbot_description
  7 packages aborted: control_msgs controller_manager_msgs ros2_control_test_assets ros2_control_test_nodes rrbot_description ur_client_library ur_dashboard_msgs
  7 packages had stderr output: control_msgs controller_manager_msgs diffbot_description ros2_control_test_assets ros2_control_test_nodes rrbot_description ur_dashboard_msgs
  26 packages not processed

**Comment by nbbrooks** [comment]
Hello - here are a few observations:

```
bash: /opt/ros/melodic/setup.bash: No such file or directory
bash: /opt/ros/notic/setup.bash: No such file or directory
```
It looks like it is trying to source some older ROS 1 distros in addition to Foxy. It isn't the cause of this issue, but you might want to clean up your .bashrc or wherever those callse are being made.

```
PermissionError: [Errno 13] Permission denied: '/home/birth/workspace/ros_ws_foxy_ur_driver/install/diffbot_description/share/diffbot_description/package.dsv'
```
It looks like you got this permissions error on a couple files. Is it possible your workspace or that package's directory was made by a different account? I would check that with `la -la /home/birth/workspace/ros_ws_foxy_ur_driver/install/diffbot_description/share/diffbot_description/package.dsv'
