### ISSUE TITLE
Using Foxy build from Source or Humble

### ISSUE THREAD

**Issue by felipebapa** [UniversalRobots/Universal_Robots_ROS2_Driver#625]
Hi! 
I am new in ros and ros2. At this moment I am trying to use the driver with [Foxy build from source](http://docs.ros.org/en/foxy/Installation/Alternatives/Ubuntu-Development-Setup.html#get-ros-2-code). I have some different errors. I don't know if this driver support this build from foxy, or if I must do something more. Thanks!

**Comment by felipebapa** [comment]
Update: I am working now in with Humble in Ubuntu 22.04, but I have a problem when I try to run a node, from the README and my own. 

First, I start the driver with `ros2 launch ur_robot_driver ur_control.launch.py ur_type:=ur5 robot_ip:=yyy.yyy.yyy.yyy use_fake_hardware:=true launch_rviz:=true`

Second, I launch the publisher with `ros2 launch ur_robot_driver test_joint_trajectory_controller.launch.py`.

I have output from the terminal, it seems to be ok. Some joint angles are showed.  But I don't see changes in the robot angles.

What should I do? Thanks!

**Comment by adnan-saood** [comment]
Don't use fake hardware, use the docker ursim instead. 

Here: https://hub.docker.com/r/universalrobots/ursim_cb3

After successfully setting up the ursim, write its IP address with the `robot_ip:=<>` argument.

If everything is successful, it should work right away.

**Comment by fmauch** [comment]
Seconding what @adnan-saood wrote. Docker with URSim is the better option to simulate the robot. However, did you look at the test node's output? There's a security check that only moves the robot if it is close to the starting position. This is to prevent users of real robots that blindly execute this script to potentially damage their robot / environment if it is mounted in a way it would collide when executing the example trajectory.

Either bring the robot close to the starting pose manually or [remove the check](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/be751913bf5b870214dcf9648a20fffa015e8687/ur_robot_driver/config/test_goal_publishers_config.yaml#L21) in the config file (if you are using a simulated robot or understand what you're doing).

We could improve in the documentation, though, hence keeping this open with the respecting label.

**Comment by adnan-saood** [comment]
I agree with you about the documentation label, when I configured the URSim last year, it was not very friendly to read from both the docker hub and the ur_driver readme.
I have to do basically the same documentation at work right now, if no one is assigned to do it I would be happy to provide it. 

best,

**Comment by fmauch** [comment]
@felipebapa Since last year we restructured a lot of the documentation, where most of the stuff is moved out of the README.md. Are you aware of our [getting started guide](https://docs.ros.org/en/ros2_packages/rolling/api/ur_robot_driver/usage.html#usage-with-official-ur-simulator)? I was more referencing towards clearly stating that for simulation purposes URSim should be best used. If you feel the guide would need some extension, feel free to contribute on it. It lives [here](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_robot_driver/doc/usage.rst).

@felipebapa The getting started guide should help you, as well. I assume, it might be a "program on the robot not started" issue, or similar. If the guide doesn't help you, please re-post all terminal output here (from the driver and the test script).

**Comment by felipebapa** [comment]
Thank you so much for your help!

The commands and the output that I have are these:

For starting the controller:

`ros2 launch ur_robot_driver ur_control.launch.py ur_type:=ur5e robot_ip:=yyy.yyy.yyy.yyy reverse_ip:=yyy.yyy.yyy.yyy use_fake_hardware:=true launch_rviz:=true`


```

[INFO] [launch]: All log files can be found below /home/felipe/.ros/log/2023-04-13-18-35-26-155649-felipe-OMEN-31934
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ros2_control_node-1]: process started with pid [31937]
[INFO] [robot_state_publisher-2]: process started with pid [31939]
[INFO] [rviz2-3]: process started with pid [31941]
[INFO] [spawner-4]: process started with pid [31943]
[INFO] [spawner-5]: process started with pid [31945]
[INFO] [spawner-6]: process started with pid [31947]
[INFO] [spawner-7]: process started with pid [31949]
[INFO] [spawner-8]: process started with pid [31951]
[INFO] [spawner-9]: process started with pid [31953]
[robot_state_publisher-2] [INFO] [1681428926.918257628] [robot_state_publisher]: got segment base
[robot_state_publisher-2] [INFO] [1681428926.918518606] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1681428926.918546155] [robot_state_publisher]: got segment base_link_inertia
[robot_state_publisher-2] [INFO] [1681428926.918561929] [robot_state_publisher]: got segment flange
[robot_state_publisher-2] [INFO] [1681428926.918575246] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-2] [INFO] [1681428926.918588461] [robot_state_publisher]: got segment ft_frame
[robot_state_publisher-2] [INFO] [1681428926.918601011] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-2] [INFO] [1681428926.918613599] [robot_state_publisher]: got segment tool0
[robot_state_publisher-2] [INFO] [1681428926.918625650] [robot_state_publisher]: got segment upper_arm_link
[robot_state_publisher-2] [INFO] [1681428926.918640915] [robot_state_publisher]: got segment world
[robot_state_publisher-2] [INFO] [1681428926.918653551] [robot_state_publisher]: got segment wrist_1_link
[robot_state_publisher-2] [INFO] [1681428926.918668525] [robot_state_publisher]: got segment wrist_2_link
[robot_state_publisher-2] [INFO] [1681428926.918681481] [robot_state_publisher]: got segment wrist_3_link
[ros2_control_node-1] [INFO] [1681428926.926759970] [resource_manager]: Loading hardware 'ur5e' 
[ros2_control_node-1] [INFO] [1681428926.928472532] [resource_manager]: Initialize hardware 'ur5e' 
[ros2_control_node-1] [WARN] [1681428926.928564290] [mock_generic_system]: Parsing of optional initial interface values failed or uses a deprecated format. Add initial values for every state interface in the ros2_control.xacro. For example: 
[ros2_control_node-1] <state_interface name="velocity"> 
[ros2_control_node-1]   <param name="initial_value">0.0</param> 
[ros2_control_node-1] </state_interface>
[ros2_control_node-1] [INFO] [1681428926.928644611] [resource_manager]: Successful initialization of hardware 'ur5e'
[ros2_control_node-1] [INFO] [1681428926.928937826] [resource_manager]: 'configure' hardware 'ur5e' 
[ros2_control_node-1] [INFO] [1681428926.928953964] [resource_manager]: Successful 'configure' of hardware 'ur5e'
[ros2_control_node-1] [INFO] [1681428926.929002580] [resource_manager]: 'activate' hardware 'ur5e' 
[ros2_control_node-1] [INFO] [1681428926.929012248] [resource_manager]: Successful 'activate' of hardware 'ur5e'
[ros2_control_node-1] [INFO] [1681428926.937732077] [controller_manager]: update rate is 500 Hz
[ros2_control_node-1] [INFO] [1681428926.941828486] [controller_manager]: RT kernel is recommended for better performance
[ros2_control_node-1] [INFO] [1681428927.567302208] [controller_manager]: Loading controller 'force_torque_sensor_broadcaster'
[ros2_control_node-1] [INFO] [1681428927.588266108] [controller_manager]: Loading controller 'joint_state_broadcaster'
[ros2_control_node-1] [INFO] [1681428927.609494180] [controller_manager]: Loading controller 'forward_position_controller'
[spawner-8] [INFO] [1681428927.620037146] [spawner_force_torque_sensor_broadcaster]: Loaded force_torque_sensor_broadcaster
[ros2_control_node-1] [INFO] [1681428927.627149815] [controller_manager]: Loading controller 'scaled_joint_trajectory_controller'
[spawner-5] [INFO] [1681428927.644345801] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ros2_control_node-1] [INFO] [1681428927.647859038] [controller_manager]: Loading controller 'io_and_status_controller'
[spawner-9] [INFO] [1681428927.658720656] [spawner_forward_position_controller]: Loaded forward_position_controller
[ros2_control_node-1] [INFO] [1681428927.660069308] [controller_manager]: Loading controller 'speed_scaling_state_broadcaster'
[ros2_control_node-1] [INFO] [1681428927.677720879] [controller_manager]: Configuring controller 'force_torque_sensor_broadcaster'
[ros2_control_node-1] [INFO] [1681428927.679850056] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-1] [INFO] [1681428927.679911828] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[spawner-4] [INFO] [1681428927.683393771] [spawner_scaled_joint_trajectory_controller]: Loaded scaled_joint_trajectory_controller
[ros2_control_node-1] [INFO] [1681428927.685486873] [controller_manager]: Configuring controller 'forward_position_controller'
[ros2_control_node-1] [INFO] [1681428927.686588815] [forward_position_controller]: configure successful
[ros2_control_node-1] [INFO] [1681428927.687146066] [controller_manager]: Configuring controller 'scaled_joint_trajectory_controller'
[ros2_control_node-1] [INFO] [1681428927.687316586] [scaled_joint_trajectory_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ros2_control_node-1] [INFO] [1681428927.687371112] [scaled_joint_trajectory_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ros2_control_node-1] [INFO] [1681428927.687404873] [scaled_joint_trajectory_controller]: Using 'splines' interpolation method.
[ros2_control_node-1] [INFO] [1681428927.688580698] [scaled_joint_trajectory_controller]: Controller state will be published at 100.00 Hz.
[ros2_control_node-1] [INFO] [1681428927.689963856] [scaled_joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[spawner-6] [INFO] [1681428927.692197622] [spawner_io_and_status_controller]: Loaded io_and_status_controller
[ros2_control_node-1] [INFO] [1681428927.698505734] [controller_manager]: Configuring controller 'io_and_status_controller'
[spawner-8] [INFO] [1681428927.704329184] [spawner_force_torque_sensor_broadcaster]: Configured and activated force_torque_sensor_broadcaster
[spawner-5] [INFO] [1681428927.708679546] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[spawner-4] [INFO] [1681428927.712493035] [spawner_scaled_joint_trajectory_controller]: Configured and activated scaled_joint_trajectory_controller
[spawner-7] [INFO] [1681428927.714766307] [spawner_speed_scaling_state_broadcaster]: Loaded speed_scaling_state_broadcaster
[ros2_control_node-1] [INFO] [1681428927.735572504] [controller_manager]: Configuring controller 'speed_scaling_state_broadcaster'
[ros2_control_node-1] [INFO] [1681428927.735688520] [speed_scaling_state_broadcaster]: Publisher rate set to : 100.0 Hz
[spawner-6] [INFO] [1681428927.736666238] [spawner_io_and_status_controller]: Configured and activated io_and_status_controller
[spawner-7] [INFO] [1681428927.747261450] [spawner_speed_scaling_state_broadcaster]: Configured and activated speed_scaling_state_broadcaster
[rviz2-3] [INFO] [1681428927.815782521] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [1681428927.816141982] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-3] [INFO] [1681428927.862038285] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [spawner-9]: process has finished cleanly [pid 31953]
[INFO] [spawner-5]: process has finished cleanly [pid 31945]
[INFO] [spawner-4]: process has finished cleanly [pid 31943]
[INFO] [spawner-8]: process has finished cleanly [pid 31951]
[INFO] [spawner-6]: process has finished cleanly [pid 31947]
[INFO] [spawner-7]: process has finished cleanly [pid 31949]
```
For launching an example node in another terminal:

`ros2 launch ur_robot_driver test_joint_trajectory_controller.launch.py`

```
[INFO] [launch]: All log files can be found below /home/felipe/.ros/log/2023-04-13-18-41-53-150393-felipe-OMEN-32247
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [publisher_joint_trajectory_controller-1]: process started with pid [32248]
[publisher_joint_trajectory_controller-1] [WARN] [1681429313.659676471] [publisher_joint_trajectory_controller]: Goal "pos1" is defined as a list. This is deprecated. Use the following structure:
[publisher_joint_trajectory_controller-1] <goal_name>:
[publisher_joint_trajectory_controller-1]   positions: [joint1, joint2, joint3, ...]
[publisher_joint_trajectory_controller-1]   velocities: [v_joint1, v_joint2, ...]
[publisher_joint_trajectory_controller-1]   accelerations: [a_joint1, a_joint2, ...]
[publisher_joint_trajectory_controller-1]   effort: [eff_joint1, eff_joint2, ...]
[publisher_joint_trajectory_controller-1] [WARN] [1681429313.660546387] [publisher_joint_trajectory_controller]: Goal "pos2" is defined as a list. This is deprecated. Use the following structure:
[publisher_joint_trajectory_controller-1] <goal_name>:
[publisher_joint_trajectory_controller-1]   positions: [joint1, joint2, joint3, ...]
[publisher_joint_trajectory_controller-1]   velocities: [v_joint1, v_joint2, ...]
[publisher_joint_trajectory_controller-1]   accelerations: [a_joint1, a_joint2, ...]
[publisher_joint_trajectory_controller-1]   effort: [eff_joint1, eff_joint2, ...]
[publisher_joint_trajectory_controller-1] [WARN] [1681429313.661329400] [publisher_joint_trajectory_controller]: Goal "pos3" is defined as a list. This is deprecated. Use the following structure:
[publisher_joint_trajectory_controller-1] <goal_name>:
[publisher_joint_trajectory_controller-1]   positions: [joint1, joint2, joint3, ...]
[publisher_joint_trajectory_controller-1]   velocities: [v_joint1, v_joint2, ...]
[publisher_joint_trajectory_controller-1]   accelerations: [a_joint1, a_joint2, ...]
[publisher_joint_trajectory_controller-1]   effort: [eff_joint1, eff_joint2, ...]
[publisher_joint_trajectory_controller-1] [WARN] [1681429313.662000969] [publisher_joint_trajectory_controller]: Goal "pos4" is defined as a list. This is deprecated. Use the following structure:
[publisher_joint_trajectory_controller-1] <goal_name>:
[publisher_joint_trajectory_controller-1]   positions: [joint1, joint2, joint3, ...]
[publisher_joint_trajectory_controller-1]   velocities: [v_joint1, v_joint2, ...]
[publisher_joint_trajectory_controller-1]   accelerations: [a_joint1, a_joint2, ...]
[publisher_joint_trajectory_controller-1]   effort: [eff_joint1, eff_joint2, ...]
[publisher_joint_trajectory_controller-1] [INFO] [1681429313.662336326] [publisher_joint_trajectory_controller]: Publishing 4 goals on topic "/joint_trajectory_controller/joint_trajectory" every {wait_sec_between_publish} s
[publisher_joint_trajectory_controller-1] [INFO] [1681429319.672141488] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.785, -1.57, 0.785, 0.785, 0.785, 0.785], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429325.664662086] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, 0.0, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429331.664618915] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, -0.785, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429337.664635788] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, 0.0, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429343.664656129] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.785, -1.57, 0.785, 0.785, 0.785, 0.785], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429349.664670633] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, 0.0, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429355.664590807] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, -0.785, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429361.664674958] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, 0.0, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429367.664634923] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.785, -1.57, 0.785, 0.785, 0.785, 0.785], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429373.664653939] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, 0.0, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429379.664755997] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, -0.785, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429385.664666142] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, 0.0, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429391.664806562] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.785, -1.57, 0.785, 0.785, 0.785, 0.785], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429397.664625978] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, 0.0, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429403.664679212] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, -0.785, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429409.664574895] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, 0.0, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429415.664621924] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.785, -1.57, 0.785, 0.785, 0.785, 0.785], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429421.664578560] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, 0.0, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
[publisher_joint_trajectory_controller-1] [INFO] [1681429427.664686401] [publisher_joint_trajectory_controller]: Sending goal trajectory_msgs.msg.JointTrajectoryPoint(positions=[0.0, -1.57, 0.0, 0.0, -0.785, 0.0], velocities=[], accelerations=[], effort=[], time_from_start=builtin_interfaces.msg.Duration(sec=4, nanosec=0)).
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[publisher_joint_trajectory_controller-1] Traceback (most recent call last):
[publisher_joint_trajectory_controller-1]   File "/home/felipe/workspace/ros_ur_driver/install/ros2_controllers_test_nodes/lib/ros2_controllers_test_nodes/publisher_joint_trajectory_controller", line 33, in <module>
[publisher_joint_trajectory_controller-1]     sys.exit(load_entry_point('ros2-controllers-test-nodes==2.17.2', 'console_scripts', 'publisher_joint_trajectory_controller')())
[publisher_joint_trajectory_controller-1]   File "/home/felipe/workspace/ros_ur_driver/install/ros2_controllers_test_nodes/lib/python3.10/site-packages/ros2_controllers_test_nodes/publisher_joint_trajectory_controller.py", line 213, in main
[publisher_joint_trajectory_controller-1]     rclpy.spin(publisher_joint_trajectory)
[publisher_joint_trajectory_controller-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
[publisher_joint_trajectory_controller-1]     executor.spin_once()
[publisher_joint_trajectory_controller-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 705, in spin_once
[publisher_joint_trajectory_controller-1]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[publisher_joint_trajectory_controller-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 691, in wait_for_ready_callbacks
[publisher_joint_trajectory_controller-1]     return next(self._cb_iter)
[publisher_joint_trajectory_controller-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 534, in _wait_for_ready_callbacks
[publisher_joint_trajectory_controller-1]     context_stack.enter_context(srv.handle)
[publisher_joint_trajectory_controller-1]   File "/usr/lib/python3.10/contextlib.py", line 492, in enter_context
[publisher_joint_trajectory_controller-1]     result = _cm_type.__enter__(cm)
[publisher_joint_trajectory_controller-1] KeyboardInterrupt
[ERROR] [publisher_joint_trajectory_controller-1]: process has died [pid 32248, exit code -2, cmd '/home/felipe/workspace/ros_ur_driver/install/ros2_controllers_test_nodes/lib/ros2_controllers_test_nodes/publisher_joint_trajectory_controller --ros-args -r __node:=publisher_joint_trajectory_controller --params-file /home/felipe/workspace/ros_ur_driver/install/ur_robot_driver/share/ur_robot_driver/config/test_goal_publishers_config.yaml'].
```

These are the steps that I used when I was working with Foxy, and the robot response was the expected. Different joint angles configurations.

Now, working with Humble, the robot model in RVIZ2, real robot and URSIM are not responding.

 I followed the steps of the guide and the Humble Branch README, with a succesfull build.

**Comment by destogl** [comment]
@felipebapa you should use, because per default scaled controller is started.

```
ros2 launch ur_robot_driver test_scaled_joint_trajectory_controller.launch.py
```.

**Comment by VinDp** [comment]
I will close this issue, since it's rather old and a solution was proposed.
Feel free to reopen in case it's still relevant.
